-- CREATE TABLE import_logs (
--    id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
--    created_at DATETIME NOT NULL DEFAULT GETDATE(),
--    status VARCHAR(255) NOT NULL

-- );

CREATE TABLE import_logs_new (
   id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   tool VARCHAR(50) NOT NULL,
   gp_system VARCHAR(10) NOT NULL,
   ip_address VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
   ods_code VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
   status VARCHAR(10) NOT NULL,
   import_date DATE NOT NULL DEFAULT GETDATE(),
   import_time TIME(0) NOT NULL DEFAULT CAST(GETDATE() AS TIME)
)
